### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by mgu** [peopledoc/septentrion#4]
To Do:

- [x] Add black and isort, add a CI (travis ? circle ?): #6
- [x] Convert csv parameters to list in click (e.g. ADDITIONAL_SCHEMA_FILES): #7 
- [x] Fix relative import bug in python 2: #7 
- [x] Understand why WEST_PASSWORD doesn't work: #7 
- [x] Rework logs/print/outputs and add logging everywhere: #7 
- [x] Embed `west init` into `west migrate` when applicable: #7 
- [x] Make `west fake` as a separate command: #7 
- [x] Unify stdout with `click.style` everywhere we need it (improved in #7)
- [x] And obviously, write (py-)tests, loads of 'em, unit, functional, acceptance tests, compute our coverage and make it a big number
- [ ] Write documentation (see Daniele Procida's talk on how to organize a good technical documentation)
- [ ] Contributing doc too
- [x] Publish on PyPI ! before the name is taken by someone else
- [ ] Communicate around the project

**Comment by ewjoachim** [comment]
Let's say we've done enough here and start a new list
